services:
  product-service:
    build:
      context: .
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=ProductDb;User=sa;Password=123Fr4nk!;Encrypt=false;
